CacheExpires: "672h"  # 4 weeks
DirectoryPath: public/
EnforceHTTPS: true
ExternalTimeout: 60
HTTPConcurrencyLimit: 32
HTTPHeaders:
  User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
IgnoreCanonicalBrokenLinks: false
IgnoreHTTPS:
  - "http://bei\\.umontreal\\.ca"
  - "http://jur\\.byu\\.edu"
  - "http://www\\.ahc\\.umontreal\\.ca/ActivitesJumelage/interlinguistique\\.htm"
  - "^http://www\\.faecum\\.qc\\.ca/$"
IgnoreURLs:
  # these consistently return weird status codes:
  - "^https://openreview\\.net/pdf\\?id=ryxWIgBFPS$"
  - "^https://www\\.pnas\\.org/doi/10\\.1073/pnas\\.2016976118$"
  - "^https://www\\.linkedin\\.com/in/kyle-roth/$"
  - "^https://www\\.wsj\\.com/articles/futures-exchange-reins-in-runaway-trading-algorithms-11572377375$"
  # onion sites
  - "http://.*\\.onion"
  # expired HTTPS cert
  - "https://5kids1condo\\.com/access-the-good-life-dont-own-it/"
