baseURL = "http://kylrth.com"
languageCode = "en-us"
title = "Kyle Roth"

copyright = "&copy; Kyle Roth"

[params]
  twitter = "kylrth"
  github = "kylrth"
  linkedin = "kyle-roth"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2
