baseURL = "https://kylrth.com/"
languageCode = "en-us"
title = "Kyle Roth"
paginate = 5
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # allow LaTeX display mode

[taxonomies]
  tag = "tags"

[params]
  defaultAuthor = "Kyle Roth"

  rss = true
  github = "kylrth"
  linkedin = "kyle-roth"
  matrix = "@kyle:kylrth.com"

[[menu.main]]
    name = "homepage"
    url = "/"
    weight = 1

[[menu.main]]
    name = "posts"
    url = "/post/"
    weight = 2

[[menu.main]]
    name = "paper notes"
    url = "/paper/"
    weight = 3

[[menu.main]]
    name = "book notes"
    url = "/book/"
    weight = 4

[related]
  threshold = 60
  includeNewer = true
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
