version: "3.9"

# based on an example found here: https://jonnev.se/matrix-homeserver-with-docker/

services:
  nginx:
    image: nginx:1.23.3-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/www:/etc/www:ro
    ports:
      - "80:80"
      - "443:443"
  # the certbot container won't start unless asked (like if we're renewing a cert)
  certbot:
    image: certbot/certbot
    profiles:
      - cert_renew  # don't start this container unless explicitly asked
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  postgres:
    image: postgres:13  # arm32v7/postgres:13 on arm64
    user: 1000:1000
    restart: unless-stopped
    networks:
      - postgres
    volumes:
     - ./data/postgres:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=some password
     - POSTGRES_USER=synapse
     - POSTGRES_INITDB_ARGS=--locale C --encoding UTF8
  synapse:
    image: matrixdotorg/synapse:v1.78.0  # you'll have to find an arm64 image for this
    restart: unless-stopped
    depends_on:
     - postgres
    networks:
      - default
      - postgres
    volumes:
     - ./data/synapse:/data
    environment:
     UID: 1000
     GID: 1000

  maubot:
    image: dock.mau.dev/maubot/maubot:v0.4.0  # instructions to build for arm64: https://hub.docker.com/r/kylrth/maubot
    restart: unless-stopped
    depends_on:
      - synapse
      - postgres
    networks:
      - default
      - postgres
    volumes:
     - ./data/maubot:/data
    environment:
     UID: 1000
     GID: 1000

  registration:
    image: zeratax/matrix-registration:v0.9.1  # https://github.com/kylrth/matrix-registration-docker-arm
    user: 1000:1000
    restart: unless-stopped
    depends_on:
      - synapse
    volumes:
     - ./data/registration:/data
    command: serve

networks:
  postgres:
