name: build/link check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: load htmltest cache
      id: hit-cache
      uses: actions/cache@v3
      with:
        path: tmp/.htmltest
        key: htmltest-cache

    - name: set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: download htmltest
      run: curl https://htmltest.wjdp.uk | sudo bash -s -- -b /usr/local/bin

    # build site and check links
    - name: run htmltest
      run: make htmltest

    # deploy to GitHub pages if this is the main branch
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
