name: build/link check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: restore htmltest cache
      uses: actions/cache/restore@v4
      with:
        path: tmp/.htmltest
        # We want the latest cache to hit and be updated every time.
        key: htmltest-${{ github.run_id }}
        restore-keys: |
          htmltest

    - name: set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: download htmltest
      run: curl https://htmltest.wjdp.uk | sudo bash -s -- -b /usr/local/bin

    # build site and check links
    - name: run htmltest
      run: make htmltest

    - name: save htmltest cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: tmp/.htmltest
        key: htmltest-${{ github.run_id }}

    # deploy to GitHub pages if this is the main branch
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
